services:
  postgres-db:
    image: postgres:16-alpine
    container_name: eventhub-db
    environment:
      POSTGRES_DB: eventhub_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  eventhub-api:
    build: .
    container_name: eventhub-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/eventhub_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgrespassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres-db

volumes:
  postgres_data: